# Generated by Django 2.1.1 on 2018-11-26 20:10

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import uuid
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xmlarchive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcsDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.NullBooleanField(db_index=True, default=True)),
                ('serial', models.CharField(max_length=100)),
                ('current_config_level', models.DateTimeField(blank=True, null=True)),
                ('desired_config_level', models.DateTimeField(blank=True, null=True)),
                ('current_software_version', models.CharField(blank=True, max_length=50)),
                ('desired_software_version', models.CharField(blank=True, max_length=50)),
                ('acs_xmpp_password', models.CharField(blank=True, max_length=50)),
                ('acs_latest_inform', models.DateTimeField(blank=True, null=True)),
                ('acs_parameters', models.TextField(blank=True)),
                ('acs_parameters_time', models.DateTimeField(blank=True, null=True)),
                ('imported', models.BooleanField(default=False)),
                ('acs_connectionrequest_password', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AcsDeviceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.NullBooleanField(db_index=True, default=True)),
                ('name', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('WIFI', 'Wifi Device'), ('SETTOPBOX', 'Settop Box')], default='UNKNOWN', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AcsDeviceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.NullBooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=50)),
                ('desired_config_level', models.DateTimeField(blank=True, null=True)),
                ('desired_software_version', models.CharField(blank=True, max_length=50)),
                ('acs_parameter_map_overrides', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='acsdevicemodels', to='acs.AcsDeviceCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcsDeviceVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.NullBooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=100)),
                ('oui', models.CharField(max_length=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcsHttpRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.NullBooleanField(db_index=True, default=True)),
                ('db_body', models.TextField(blank=True)),
                ('cwmp_id', models.CharField(blank=True, max_length=100)),
                ('cwmp_rpc_method', models.CharField(blank=True, max_length=100)),
                ('request_headers', models.TextField(blank=True)),
                ('request_xml_valid', models.BooleanField(default=False)),
                ('request_soap_valid', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='AcsHttpResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.NullBooleanField(db_index=True, default=True)),
                ('db_body', models.TextField(blank=True)),
                ('cwmp_id', models.CharField(blank=True, max_length=100)),
                ('cwmp_rpc_method', models.CharField(blank=True, max_length=100)),
                ('fk_body', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.DJANGO_ACS['xml_storage_model'])),
                ('http_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acs_http_responses', to='acs.AcsHttpRequest')),
                ('rpc_response_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rpc_responses', to='acs.AcsHttpRequest')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='AcsQueueJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.NullBooleanField(db_index=True, default=True)),
                ('cwmp_rpc_object_xml', models.TextField()),
                ('reason', models.CharField(max_length=200)),
                ('automatic', models.BooleanField(default=False)),
                ('urgent', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('acs_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acs_queue_jobs', to='acs.AcsDevice')),
                ('handled_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='queuejobs', to='acs.AcsHttpResponse')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='AcsSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.NullBooleanField(db_index=True, default=True)),
                ('acs_session_id', models.UUIDField(default=uuid.uuid4)),
                ('client_ip', models.GenericIPAddressField()),
                ('client_ip_verified', models.BooleanField(default=False)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('session_result', models.BooleanField(default=False)),
                ('latest_rpc_method', models.CharField(blank=True, default='', max_length=100)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('_device_uptime', django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, null=True)),
                ('inform_eventcodes', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('cwmp_namespace', models.CharField(blank=True, default='', max_length=100)),
                ('acs_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acs_sessions', to='acs.AcsDevice')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='CwmpDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.NullBooleanField(db_index=True, default=True)),
                ('name', models.TextField()),
                ('xml_filename', models.TextField(blank=True)),
                ('html_link', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='acssession',
            name='root_data_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acs_sessions', to='acs.CwmpDataModel'),
        ),
        migrations.AddField(
            model_name='acshttprequest',
            name='acs_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acs_http_requests', to='acs.AcsSession'),
        ),
        migrations.AddField(
            model_name='acshttprequest',
            name='fk_body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='xmlarchive.XMLDocument'),
        ),
        migrations.AddField(
            model_name='acshttprequest',
            name='rpc_response_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rpc_responses', to='acs.AcsHttpResponse'),
        ),
        migrations.AddField(
            model_name='acsdevicemodel',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acsdevicemodels', to='acs.AcsDeviceVendor'),
        ),
        migrations.AlterUniqueTogether(
            name='acsdevicecategory',
            unique_together={('name', 'active')},
        ),
        migrations.AddField(
            model_name='acsdevice',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acsdevices', to='acs.AcsDeviceModel'),
        ),
        migrations.AlterUniqueTogether(
            name='acssession',
            unique_together={('acs_session_id', 'client_ip', 'active')},
        ),
        migrations.AlterUniqueTogether(
            name='acshttpresponse',
            unique_together={('http_request', 'active')},
        ),
        migrations.AlterUniqueTogether(
            name='acsdevice',
            unique_together={('serial', 'model', 'active')},
        ),
    ]
