# Generated by Django 2.1.1 on 2019-01-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acsqueuejob',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
