# Generated by Django 2.1.5 on 2019-02-18 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acshttprequest',
            old_name='cwmp_rpc_method',
            new_name='soap_element',
        ),
        migrations.RenameField(
            model_name='acshttpresponse',
            old_name='cwmp_rpc_method',
            new_name='soap_element',
        ),
    ]
