# Generated by Django 2.1.5 on 2019-02-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0002_auto_20190218_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='acsdevice',
            name='acs_inform_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acsdevice',
            name='acs_latest_session_result',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
