# Generated by Django 2.1.1 on 2019-01-31 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0002_acsqueuejob_notification_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acshttprequest',
            name='db_body',
        ),
        migrations.RemoveField(
            model_name='acshttpresponse',
            name='db_body',
        ),
    ]
